### ISSUE TITLE
Support for .265 files

### ISSUE THREAD

**Issue by littlease** [francescovannini/ipcam264convert#1]
There is a new bunch of cheap cameras on same SoC, which produced .265 files in HEVC with HX* headers. Maybe someone can put me in a right direction to adapt this code for .265 files?
This tool pointed to .265 file:
```
Unknown audio_frame header: 1414944840.
Unknown audio_frame header: 2560.
Unknown audio_frame header: 1920.
Unknown audio_frame header: 0.
Selected output format: Matroska (video/x-matroska)
Detected video frame rate: 13
Detected audio PCM frequency: 8000
[libx264 @ 0x559b160460c0] [IMGUTILS @ 0x7fffb95f17e0] Picture size 0x0 is invalid
[libx264 @ 0x559b160460c0] [IMGUTILS @ 0x7fffb95f17b0] Picture size 0x0 is invalid
[libx264 @ 0x559b160460c0] dimensions not set
Could not open codec: Invalid argument
```

Same file with -n option:
```
Unknown audio_frame header: 1414944840.
Unknown audio_frame header: 2560.
Unknown audio_frame header: 1920.
Unknown audio_frame header: 0.
Selected output format: Matroska (video/x-matroska)
Detected video frame rate: 13
Audio processing is disabled.
[libx264 @ 0x55ac77e7e0c0] dimensions not set
Could not open codec: Invalid argument
```

**Comment by francescovannini** [comment]
Could you share a few sample videos and the camera model you are using to see how hard would be to support it?

**Comment by littlease** [comment]
> Could you share a few sample videos and the camera model you are using to see how hard would be to support it?

Attached some samples [samples265.zip](https://github.com/francescovannini/ipcam264convert/files/13514004/samples265.zip). Brand name is Unitoptek, model is obscure C6F0SoZ3N0PfL2.
So far through guesswork i've managed to find that "frame header" for 265 is HXVT 1414944840 instead of HXVS 1398167624
![image](https://github.com/francescovannini/ipcam264convert/assets/3368886/55d90ad9-b3d6-4d7a-9523-33d53efba3b9)
Video and audio frames seems to be the same as for .264 files, only difference - HEVC is used for encoding.

**Comment by francescovannini** [comment]
Thanks for sharing the samples and thanks also for the guesswork, which was correct. I just merged some changes based on your suggestions and it worked the first try. Thanks a lot for your contribution! :)
